name: Test

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./src/test/resources/
        id: simple
        with:
          file: src/test/resources/test.properties
          property: name
      - uses: ./.github/actions/compare
        with:
          a: Darth Vader
          b: ${{ steps.simple.outputs.value }}

      - uses: ./src/test/resources/
        id: multiline
        with:
          file: src/test/resources/test.properties
          property: affiliation
      - uses: ./.github/actions/compare
        with:
          a: |-
            Galactic
            Empire
          b: ${{ steps.multiline.outputs.value }}

      - uses: ./src/test/resources/
        id: simple-default
        with:
          file: src/test/resources/test.properties
          property: version
          default: 1.0.0
      - uses: ./.github/actions/compare
        with:
          a: 1.0.0
          b: ${{ steps.simple-default.outputs.value }}

      - uses: ./src/test/resources/
        id: multiline-default
        with:
          file: src/test/resources/test.properties
          property: version
          default: |-
            1
            2
            3
      - uses: ./.github/actions/compare
        with:
          a: |-
            1
            2
            3
          b: ${{ steps.multiline-default.outputs.value }}

      - uses: ./src/test/resources/
        id: unexisting-file
        with:
          file: src/test/resources/unexisting.properties
          property: name
          default: Anakin Skywalker
      - uses: ./.github/actions/compare
        with:
          a: Anakin Skywalker
          b: ${{ steps.unexisting-file.outputs.value }}

      - uses: ./src/test/resources/
        id: all
        with:
          file: src/test/resources/test.properties
          all: true
      - uses: ./.github/actions/compare
        with:
          a: Darth Vader
          b: ${{ steps.all.outputs.name }}
      - uses: ./.github/actions/compare
        with:
          a: Sith Lord
          b: ${{ steps.all.outputs.occupation }}
      - uses: ./.github/actions/compare
        with:
          a: |-
            Galactic
            Empire
          b: ${{ steps.all.outputs.affiliation }}
      - uses: ./.github/actions/compare
        with:
          a: Luke Skywalker
          b: ${{ steps.all.outputs.son }}
      - uses: ./.github/actions/compare
        with:
          a: 1
          b: ${{ steps.all.outputs.read-java-properties-delimiter }}
      - uses: ./.github/actions/compare
        with:
          a: 2
          b: ${{ steps.all.outputs.read-java-properties-delimiter-x }}
      - uses: ./.github/actions/compare
        with:
          a: |-
            3
            4
          b: ${{ steps.all.outputs.read-java-properties-delimiter-x-x }}

      - uses: ./src/test/resources/
        id: failure
        with:
          file: src/test/resources/unexisting.properties
          property: name
        continue-on-error: true
      - run: '[[ "failure" == "${{ steps.failure.outcome }}" ]]'

  actions-typing:
    name: Validate actions typing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typesafegithub/github-actions-typing@v1
